app/models.py
from . import db
from werkzeug.security import generate_password_hash, check_password_hash

class Aluno(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    nome = db.Column(db.String(100), nullable=False)
    casa = db.Column(db.String(50), nullable=False)
    ano = db.Column(db.Integer, nullable=False)
    especialidades = db.Column(db.String(200), nullable=False)

    def __repr__(self):
        return f'<Aluno {self.nome}>'

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    password_hash = db.Column(db.String(128))

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

db = SQLAlchemy()


def create_app():
    app = Flask(__name__)
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///hogwarts.db'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

    db.init_app(app)
    migrate = Migrate(app, db)

    with app.app_context():
        db.create_all() 

    from .routes import main
    app.register_blueprint(main)

    app.secret_key = 'renanputao12'

    return app

app/routes.py
from flask import Blueprint, jsonify, request, render_template, redirect, url_for, flash, session
from .models import Aluno, User, db
from werkzeug.security import check_password_hash, generate_password_hash

main = Blueprint('main', __name__)

@main.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        user = User.query.filter_by(username=username).first()
        if user and check_password_hash(user.password_hash, password):
            session['user_id'] = user.id
            return redirect(url_for('main.home'))
        flash('Usuário ou senha inválidos')
    return render_template('login.html')

@main.route('/logout')
def logout():
    session.pop('user_id', None)
    return redirect(url_for('main.login'))

@main.route('/api/alunos', methods=['GET'])
def api_list_alunos():
    alunos_list = Aluno.query.all()
    alunos = [
        {'id': aluno.id, 'nome': aluno.nome, 'casa': aluno.casa, 'ano': aluno.ano, 'especialidades': aluno.especialidades}
        for aluno in alunos_list
    ]
    return jsonify(alunos)

@main.route('/alunos', methods=['GET'])
def show_alunos():
    alunos_list = Aluno.query.all()
    return render_template('alunos.html', alunos=alunos_list)

@main.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        password2 = request.form['password2']
        
        if password != password2:
            flash('As senhas não coincidem.')
            return render_template('register.html')
        
        user = User.query.filter_by(username=username).first()
        if user:
            flash('Usuário já existe.')
            return render_template('register.html')
        
        new_user = User(username=username)
        new_user.set_password(password)
        db.session.add(new_user)
        db.session.commit()
        flash('Usuário registrado com sucesso!')
        return redirect(url_for('main.login'))
    return render_template('register.html')

@main.route('/cadastrar', methods=['GET', 'POST'])
def cadastrar():
    if request.method == 'POST':
        data = request.get_json(force=True) 
        if not data:
            return jsonify({'message': 'No JSON payload provided'}), 400
        try:
            novo_aluno = Aluno(nome=data['nome'], casa=data['casa'], ano=data['ano'], especialidades=data.get('especialidades', ''))
            db.session.add(novo_aluno)
            db.session.commit()
            return jsonify({'message': 'Aluno adicionado com sucesso!'}), 201
        except Exception as e:
            return jsonify({'message': 'Erro ao salvar no banco de dados', 'error': str(e)}), 500
    else:
        return render_template('cadastrar.html')

@main.route('/')
def home():
    user_id = session.get('user_id')
    if not user_id:
        return redirect(url_for('main.login'))
    return render_template('home.html')

@main.route('/alunos/<int:id>/edit', methods=['GET'])
def edit_aluno(id):
    aluno = Aluno.query.get_or_404(id)
    return render_template('edit_aluno.html', aluno=aluno)

@main.route('/alunos/<int:id>/update', methods=['POST'])
def update_aluno(id):
    aluno = Aluno.query.get_or_404(id)
    aluno.nome = request.form['nome']
    aluno.casa = request.form['casa']
    aluno.ano = request.form['ano']
    aluno.especialidades = request.form['especialidades']
    db.session.commit()
    return redirect('/alunos')


@main.route('/alunos/<int:id>/delete', methods=['POST'])
def delete_aluno(id):
    aluno = Aluno.query.get_or_404(id)
    db.session.delete(aluno)
    db.session.commit()
    return redirect ('/alunos')

app/templates/alunos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista de Alunos</title>
    <link rel="icon" type="image/x-icon" href="/static/images/hogwarts_logo.png">
    <link rel="stylesheet" href="/static/styles.css">
    <link href="https://fonts.googleapis.com/css2?family=Cinzel&display=swap" rel="stylesheet">
</head>
<header>
    <a href="/"><img src="/static/images/hogwarts_logo.png" alt="Logo de Hogwarts" style="height: 200px;"></a>
    <h1>Sistema de Matrículas de Hogwarts</h1>
</header>
<body>
    <h1>Lista de Alunos</h1>
    <a href="/">Voltar ao início</a>
    <ul>
        {% for aluno in alunos %}
        <li class="aluno-container">{{ aluno.nome }} - {{ aluno.casa }} - Ano: {{ aluno.ano }} - Matéria: {{ aluno.especialidades }}
            <form action="/alunos/{{ aluno.id }}/delete" method="post">
                <input type="submit" value="Delete">
            </form>
            <a href="/alunos/{{ aluno.id }}/edit" class="edit-link">Editar</a>
        </li>
        {% endfor %}
    </ul>
</body>
<footer>
    <p>© 2024 Escola de M[agia e Bruxaria de Hogwarts</p>
</footer>
</html>

app/templates/cadastrar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastrar Aluno</title>
    <link rel="icon" type="image/x-icon" href="/static/images/hogwarts_logo.png">
    <link rel="stylesheet" href="/static/styles.css">
    <link href="https://fonts.googleapis.com/css2?family=Cinzel&display=swap" rel="stylesheet">
</head>
<header>
    <a href="/"><img src="/static/images/hogwarts_logo.png" alt="Logo de Hogwarts" style="height: 200px;"></a>
    <h1>Sistema de Matrículas de Hogwarts</h1>
</header>
<body>
    <h1>Cadastrar Novo Aluno</h1>
    <form id="cadastroForm" onsubmit="submitForm(event)">
        <label for="nome">Nome:</label>
        <input type="text" id="nome" name="nome"><br>
        
        <label for="casa">Casa:</label>
        <select id="casa" name="casa">
            <option value="Grifinória">Grifinória</option>
            <option value="Sonserina">Sonserina</option>
            <option value="Corvinal">Corvinal</option>
            <option value="Lufa-Lufa">Lufa-Lufa</option>
        </select><br>

        <label for="ano">Ano:</label>
        <input type="number" id="ano" name="ano" min="1" max="7"><br>
        
        <label for="especialidades">Matéria:</label>
    <select id="especialidades" name="especialidades">
        <option value="Defesa Contra as Artes das Trevas">Defesa Contra as Artes das Trevas</option>
        <option value="Poções">Poções</option>
        <option value="Transfiguração">Transfiguração</option>
        <option value="Voo">Voo</option>
        <option value="Feitiços">Feitiços</option>
        <option value="Herbologia">Herbologia</option>
    </select><br>
        
        <input type="submit" value="Cadastrar">
    </form>
    <a href="/">Voltar ao início</a>

    <script>
        function submitForm(event) {
            event.preventDefault(); 
            const form = document.getElementById('cadastroForm');
            const formData = new FormData(form);
            const jsonData = {};
            formData.forEach((value, key) => {
                jsonData[key] = value;
            });
    
            fetch('/cadastrar', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify(jsonData)
            })
            .then(response => {
                if (response.ok) {
                    return response.json();
                } else {
                    throw new Error('Algo deu errado no servidor');
                }
            })
            .then(data => {
                alert("Aluno cadastrado com sucesso!");
                window.location.href = '/alunos';
            })
            .catch(error => {
                console.error('Error:', error);
                alert("Erro ao cadastrar aluno: " + error.message);
            });
        }
    </script>
</body>
<footer>
    <p>© 2024 Escola de M[agia e Bruxaria de Hogwarts</p>
</footer>
</html>

app/templates/edit_aluno.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar Aluno</title>
    <link rel="icon" type="image/x-icon" href="/static/images/hogwarts_logo.png">
    <link rel="stylesheet" href="/static/styles.css">
    <link href="https://fonts.googleapis.com/css2?family=Cinzel&display=swap" rel="stylesheet">
</head>
<header>
    <a href="/"><img src="/static/images/hogwarts_logo.png" alt="Logo de Hogwarts" style="height: 200px;"></a>
    <h1>Sistema de Matrículas de Hogwarts</h1>
</header>
<body>
    <h1>Editar Aluno</h1>
    <form action="/alunos/{{ aluno.id }}/update" method="post">
        <label for="nome">Nome:</label>
        <input type="text" id="nome" name="nome" value="{{ aluno.nome }}"><br>
        <label for="casa">Casa:</label>
        <input type="text" id="casa" name="casa" value="{{ aluno.casa }}"><br>
        <label for="ano">Ano:</label>
        <input type="number" id="ano" name="ano" value="{{ aluno.ano }}"><br>
        <label for="especialidades">Especialidades:</label>
        <input type="text" id="especialidades" name="especialidades" value="{{ aluno.especialidades }}"><br>
        <input type="submit" value="Atualizar">
    </form>
    <a href="/">Voltar ao início</a>
</body>
<footer>
    <p>© 2024 Escola de M[agia e Bruxaria de Hogwarts</p>
</footer>
</html>

app/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bruxos e Bruxas de Hogwarts</title>
    <link rel="icon" type="image/x-icon" href="/static/images/hogwarts_logo.png">
    <link rel="stylesheet" href="/static/styles.css">
    <link href="https://fonts.googleapis.com/css2?family=Cinzel&display=swap" rel="stylesheet">

</head>
<header>
    <a  href="/"><img src="/static/images/hogwarts_logo.png" alt="Logo de Hogwarts" style="height: 200px;"></a>
    <h1>Sistema de Matrículas de Hogwarts</h1>
</header>
<body>
    <h1>Bem-vindo ao Sistema de Matrículas de Hogwarts</h1>
    <nav>
        <ul>
            <li><a href="/alunos">Ver Alunos</a></li>
            <br>
            <li><a href="/cadastrar">Cadastrar Aluno</a></li>
        </ul>
    </nav>
</body>
<footer>
    <p>© 2024 Escola de M[agia e Bruxaria de Hogwarts</p>
</footer>
</html>

app/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login - Bruxos e Bruxas de Hogwarts</title>
    <link rel="stylesheet" href="/static/styles.css">
    <link href="https://fonts.googleapis.com/css2?family=Cinzel&display=swap" rel="stylesheet">
</head>
<body>
    <h1>Login</h1>
    <form action="/login" method="post">
        <label for="username">Usuário:</label>
        <input type="text" id="username" name="username" required>
        <label for="password">Senha:</label>
        <input type="password" id="password" name="password" required>
        <input type="submit" value="Entrar">
    </form>
</body>
</html>

app/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registro - Bruxos e Bruxas de Hogwarts</title>
    <link rel="stylesheet" href="/static/styles.css">
    <link href="https://fonts.googleapis.com/css2?family=Cinzel&display=swap" rel="stylesheet">
</head>
<body>
    <h1>Registro</h1>
    <form action="{{ url_for('main.register') }}" method="post">
        <label for="username">Usuário:</label>
        <input type="text" id="username" name="username" required>
        <label for="password">Senha:</label>
        <input type="password" id="password" name="password" required>
        <label for="password2">Confirme a Senha:</label>
        <input type="password" id="password2" name="password2" required>
        <input type="submit" value="Registrar">
    </form>
</body>
</html>